spring.application.name=UberReviewService

#what is the url of the database server
spring.datasource.url=jdbc:mariadb://localhost:3306/Uber_Db_Local


spring.datasource.username=luffy

spring.datasource.password=Plmoknijb@123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true